import { IUser, IUserMini } from "@/types/user";

export interface BoardFiltersReq {
    search?: string;
    assigneeId?: number;
    priority?: number;
}

export type IKanbanComment = {
    id: number;
    message: string;
    creator: {
        id: number;
        firstName: string;
        lastName: string;
        avatar: string;
    };
    createdAt: string;
};

export type IKanbanCommentPOST = Omit<
    IKanbanComment,
    "id" | "creator" | "createdAt"
> & {
    id?: number;
    creatorId: number;
};

export type IKanbanCard = {
    id: number;
    code: string; // INFO: automatically generated by BE
    priority: number;
    name: string;
    description: string;
    due: [string, string];
    attachments: string[];
    comments: IKanbanComment[];
    completed: boolean;

    assignee: IUser;
    propertyId: number;
    customerId: number;
    reporterId: number;

    eventId: string; // INFO: Calendar Event Id -> Google Calendar Event Id

    createdAt: string;
    updatedAt: string;
};

interface IKanbanCardShort {
    id: number;
    name: string;
    uniqueCode: string;
    priority: number;
    attachmentsCount: number;
    commentsCount: number;
    completed: boolean;
    assignees: IUserMini[];
    createdAt: string;
}

// INFO: sent to Backend directly
export type IKanbanCardPOST = {
    id?: number;
    priority: number;
    name: string;
    description?: string;
    due?: [string, string];
    attachments: string[];
    comments: IKanbanCommentPOST[];
    completed: boolean;

    columnId: number;

    propertyId?: number;
    customerId?: number;
    eventId?: string;
    assigneeId: number;
};

// INFO: used in form
export interface ICreateOrUpdateTaskReq extends IKanbanCardPOST {
    withCalendar: boolean;
    googleUserKey?: string; // INFO: google's worskpace user's primaryEmail used as a handle for creating a calendar event to him
}

export type IKanbanColumn = {
    id: number;
    name: string;
    cardIds: number[];
    cardOrder: number[];
};
type IKanbanColumnPOST = Partial<IKanbanColumn>;

type IKanbanBoard = {
    cards: IKanbanCardShort[];
    columns: IKanbanColumn[];
    columnOrder: number[];
};

export type { IKanbanColumnPOST, IKanbanCardShort, IKanbanBoard };
