import { IUserMini } from "@/types/user";

export interface BoardFiltersReq {
    search?: string;
    assigneeId?: number;
    priority?: number;
}

export type IKanbanComment = {
    id: number;
    message: string;
    creator: IUserMini;
    createdAt: string;
    updatedAt: string;
    edited: boolean;
};

type IKanbanCommentPOST = {
    id?: number;
    message: string;
};

interface IKanbanAttachment {
    id: number;
    url: string;
    filename: string;
    contentType: string;
    cdnUrl: string;
}

type IKanbanCard = {
    id: number;
    uniqueCode: string; // INFO: automatically generated by BE
    priority: number;
    name: string;
    description: string;
    due: [string, string];
    completed: boolean;

    assignees: IUserMini[];
    properties: { id: number; code: string; image: string }[];
    customers: Omit<IUserMini, "avatar">[];
    reporter: IUserMini;

    event: string; // INFO: Calendar Event Id -> Google Calendar Event Id

    createdAt: string;
    updatedAt: string;
};

interface IKanbanCardShort {
    id: number;
    name: string;
    uniqueCode: string;
    priority: number;
    attachmentsCount: number;
    commentsCount: number;
    completed: boolean;
    assignees: IUserMini[];
    createdAt: string;
}

// INFO: sent to Backend directly
export type IKanbanCardPOST = {
    id?: number;
    name: string;
    description?: string;
    due?: [string, string];
    priority: number;
    attachments: number[];

    columnId: number;

    properties?: number[];
    customers?: number[];
    userIds: number[];

    // INFO: supported by backend, but theoretically I should never update it!
    event?: string;
};

// INFO: used in form
export interface ICreateOrUpdateTaskReq extends IKanbanCardPOST {
    withCalendar: boolean;
    googleUserKey?: string; // INFO: google's worskpace user's primaryEmail used as a handle for creating a calendar event to him
}

type IKanbanColumn = {
    id: number;
    name: string;
    cardIds: number[];
    cardOrder: number[];
    done: boolean;
    numberOfTasks: number;
};
type IKanbanColumnPOST = Partial<IKanbanColumn>;

type IKanbanBoard = {
    columnOrder: number[];
    cards: IKanbanCardShort[];
    columns: IKanbanColumn[];
};

interface IKanbanAssigneeHistory {
    assignees: IUserMini[];
    createdAt: string;
}

export type {
    IKanbanColumn,
    IKanbanColumnPOST,
    // ...
    IKanbanCard,
    IKanbanCardShort,
    // ...
    IKanbanCommentPOST,
    // ...
    IKanbanAttachment,
    // ...
    IKanbanAssigneeHistory,
    // ...
    IKanbanBoard,
};
