import { TSorting } from "@/ui/Filters/SortBy/types";
import { IUserMini } from "@/types/user";

interface BoardFiltersReq {
    search?: string;
    assigneeId?: number;
    priority?: number;
    labels?: number[];

    sortBy?: TSorting["sortBy"];
    direction?: TSorting["direction"];
}

type IKanbanComment = {
    id: number;
    message: string;
    creator: IUserMini;
    createdAt: string;
    updatedAt: string;
    edited: boolean;
};

type IKanbanCommentPOST = {
    id?: number;
    message: string;
};

interface IKanbanAttachment {
    id: number;
    url: string;
    filename: string;
    contentType: string;
    cdnUrl: string;
}

type IKanbanCard = {
    id: number;
    uniqueCode: string; // INFO: automatically generated by BE
    columnId: number;
    priority: number;
    name: string;
    description: string;
    due: [string, string];
    completed: boolean;

    assignees: IUserMini[];
    properties: { id: number; code: string; image: string }[];
    customers: Omit<IUserMini, "avatar">[];
    reporter: IUserMini;
    updatedBy?: IUserMini;
    event: string; // INFO: Calendar Event Id -> Google Calendar Event Id

    createdAt: string;
    updatedAt: string;
};

interface IKanbanCardLabels {
    color: string;
    id: number;
    name: string;
}

interface IKanbanCardShort {
    id: number;
    name: string;
    uniqueCode: string;
    column: number;
    // ...
    priority: number;
    attachmentsCount: number;
    commentsCount: number;
    completed: boolean;
    assignees: IUserMini[];
    labels: IKanbanCardLabels[];
    createdAt: string;
    updatedAt: string;
    event?: string;
}

// INFO: sent to Backend directly
type IKanbanCardPOST = {
    id?: number;
    name: string;
    description?: string;
    due?: [string, string];
    priority: number;
    attachments: number[];

    columnId: number;

    properties?: number[];
    customers?: number[];
    userIds: number[];

    labels: number[];

    // INFO: supported by backend, but theoretically I should never update it!
    event?: string;
};

// INFO: used in form
interface ICreateOrUpdateTaskReq extends IKanbanCardPOST {
    withCalendar: boolean;
    oldUserId?: number; // INFO: assignee's id; must be passed on task w/ calendar update to facilitate moving to a different calendarId
}

type IKanbanColumn = {
    id: number;
    name: string;
    cardIds: number[];
    cardOrder: number[];
    done: boolean;
    numberOfTasks: number;
};
type IKanbanColumnPOST = Partial<IKanbanColumn>;

type IKanbanBoard = {
    columnOrder: number[];
    cards: IKanbanCardShort[];
    columns: IKanbanColumn[];
};

export interface Reporter {
    firstName: string;
    lastName: string;
    avatar?: string;
}
interface IKanbanAssigneeHistory {
    assignees: IUserMini[];
    createdAt: string;
    reporter: Reporter;
}

export type {
    IKanbanColumn,
    IKanbanColumnPOST,
    // ...
    IKanbanCard,
    IKanbanCardShort,
    IKanbanCardPOST,
    IKanbanCardLabels,
    ICreateOrUpdateTaskReq,
    // ...
    IKanbanComment,
    IKanbanCommentPOST,
    // ...
    IKanbanAttachment,
    // ...
    IKanbanAssigneeHistory,
    // ...
    IKanbanBoard,
    BoardFiltersReq,
};
