import { IAgreement } from "@/types/agreements";

const data: IAgreement[] = [
    {
        id: 1,
        propertyId: 101,
        variant: "basic",
        lang: "en",
        draft: true,
        keys: false,
        title: "Rental Agreement for Apartment 101",
        startingDate: "2024-07-01",
        expirationDate: "2025-07-01",
        availableAfter: "2024-06-25",
        manager: {
            fullname: "John Doe",
            title: "Property Manager",
            vat: "123456789",
            taxOffice: "Downtown Office",
            genComReg: "987654321",
        },
        company: {
            address: "123 Main Street, Anytown",
            homePhone: "555-1234",
            mobilePhone: "555-5678",
            email: "manager@company.com",
        },
        owner: {
            fullname: "Jane Smith",
            email: "jane.smith@example.com",
            maidenName: "Doe",
            idCardNo: "ID123456789",
            mobilePhone: "555-8765",
            vat: "987654321",
            city: "Anytown",
            street: "Maple Avenue",
            number: "12",
            actingOnMyBehalfFiller: "N/A",
        },
        property: {
            region: "Downtown",
            address: "123 Main Street",
            addressNo: "101",
            type: "Apartment",
            floor: 3,
            livingSpace: 85,
            description:
                "A beautiful downtown apartment with 2 bedrooms and a balcony.",
            price: 1200,
        },
        commissionAndDuration: {
            payment: 100,
            flatRate: 50,
            percentage: 10,
            months: 12,
            defects: "None",
        },
        additional: {
            date: "2024-06-01",
            commisionerSignature: "Commissioner Signature",
            agentSignature: "Agent Signature",
        },
    },
    {
        id: 2,
        propertyId: 202,
        variant: "purchase",
        lang: "el",
        draft: false,
        keys: true,
        title: "Sale Agreement for Office Space 202",
        startingDate: "2024-08-01",
        expirationDate: "2024-08-31",
        availableAfter: "2024-07-25",
        manager: {
            fullname: "Alice Brown",
            title: "Sales Manager",
            vat: "223344556",
            taxOffice: "Uptown Office",
            genComReg: "667788990",
        },
        company: {
            address: "456 Elm Street, Uptown",
            homePhone: "555-2345",
            mobilePhone: "555-6789",
            email: "sales@company.com",
        },
        owner: {
            fullname: "Robert Johnson",
            email: "robert.johnson@example.com",
            maidenName: "Smith",
            idCardNo: "ID987654321",
            mobilePhone: "555-9876",
            vat: "112233445",
            city: "Uptown",
            street: "Oak Boulevard",
            number: "45",
            actingOnMyBehalfFiller: "N/A",
        },
        property: {
            region: "Uptown",
            address: "456 Elm Street",
            addressNo: "202",
            type: "Office",
            floor: 5,
            livingSpace: 150,
            description:
                "A spacious commercial office space with modern amenities.",
            price: 250000,
        },
        commissionAndDuration: {
            payment: 5000,
            flatRate: 2000,
            percentage: 5,
            months: 1,
            defects: "Minor wear and tear",
        },
        gdpr: {
            email: "privacy@company.com",
            address: "456 Elm Street, Uptown",
        },
        additional: {
            date: "2024-07-15",
            commisionerSignature: "Commissioner Signature",
            agentSignature: "Agent Signature",
        },
    },
];

export default data;
