export const actions = [
    "create",
    "view",
    "edit",
    "delete",
    "accessOwner",
    "accessLocation",
    "accessPrice",
    "accessActive",
    "accessInactive",
    "accessHidden",
];

export enum ActionsHeadCells {
    create = "create",
    view = "view",
    edit = "edit",
    delete = "delete",
    accessOwner = "accessOwner",
    accessLocation = "accessLocation",
    accessPrice = "accessPrice",
    accessActive = "accessActive",
    accessInactive = "accessInactive",
    accessHidden = "accessHidden",
}
export enum ActionsHeadCellsLabels {
    create = "Create Permission",
    view = "View Permission",
    edit = "Edit Permission",
    delete = "Delete Permission",
    accessOwner = "See owner Permission",
    accessLocation = "See location Permission",
    accessPrice = "See price Permission",
    accessActive = "See active Permission",
    accessInactive = "See inactive Permission",
    accessHidden = "See hidden Permission",
}

export const categories = ["Residential", "Commercial", "Land", "Other"];
export const subcategories1 = [
    "Apartment",
    "Studio",
    "Maisonette",
    "Detached",
    "Villa",
    "Loft",
    "Bungalow",
    "Building",
    "Apartment complex",
    "Farm",
    "Houseboat",
    "Other residential",
];
export const subcategories2 = [
    "Office",
    "Store",
    "Warehouse",
    "Industrial space",
    "Craft space",
    "Hotel",
    "Business building",
    "Hall",
    "Showroom",
    "Other commercial",
];
export const subcategories3 = ["Plot", "Parcel", "Island", "Other land"];
export const subcategories4 = [
    "Parking Spot",
    "Business",
    "Prefabricated",
    "Detachable",
    "Air",
    "Other",
];

export enum StateTypes {
    SALE = "Sale",
    RENT = "Rent",
    SOLD_RENTED = "Sold/Rented",
}

export const initRoles = [
    {
        state: "Sale",
        parentCategory: "Residential",
        category: "Apartment",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Residential",
        category: "Studio",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Residential",
        category: "Maisonette",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Residential",
        category: "Detached",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Residential",
        category: "Villa",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Residential",
        category: "Loft",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Residential",
        category: "Bungalow",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Residential",
        category: "Building",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Residential",
        category: "Apartment complex",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Residential",
        category: "Farm",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Residential",
        category: "Houseboat",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Residential",
        category: "Other residential",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Commercial",
        category: "Office",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Commercial",
        category: "Store",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Commercial",
        category: "Warehouse",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Commercial",
        category: "Industrial space",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Commercial",
        category: "Craft space",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Commercial",
        category: "Hotel",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Commercial",
        category: "Business building",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Commercial",
        category: "Hall",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Commercial",
        category: "Showroom",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Commercial",
        category: "Other commercial",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Land",
        category: "Plot",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Land",
        category: "Parcel",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Land",
        category: "Island",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Land",
        category: "Other land",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Other",
        category: "Parking Spot",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Other",
        category: "Business",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Other",
        category: "Prefabricated",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Other",
        category: "Detachable",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Other",
        category: "Air",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sale",
        parentCategory: "Other",
        category: "Other",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Residential",
        category: "Apartment",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Residential",
        category: "Studio",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Residential",
        category: "Maisonette",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Residential",
        category: "Detached",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Residential",
        category: "Villa",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Residential",
        category: "Loft",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Residential",
        category: "Bungalow",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Residential",
        category: "Building",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Residential",
        category: "Apartment complex",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Residential",
        category: "Farm",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Residential",
        category: "Houseboat",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Residential",
        category: "Other residential",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Commercial",
        category: "Office",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Commercial",
        category: "Store",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Commercial",
        category: "Warehouse",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Commercial",
        category: "Industrial space",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Commercial",
        category: "Craft space",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Commercial",
        category: "Hotel",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Commercial",
        category: "Business building",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Commercial",
        category: "Hall",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Commercial",
        category: "Showroom",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Commercial",
        category: "Other commercial",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Land",
        category: "Plot",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Land",
        category: "Parcel",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Land",
        category: "Island",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Land",
        category: "Other land",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Other",
        category: "Parking Spot",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Other",
        category: "Business",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Other",
        category: "Prefabricated",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Other",
        category: "Detachable",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Other",
        category: "Air",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Rent",
        parentCategory: "Other",
        category: "Other",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Residential",
        category: "Apartment",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Residential",
        category: "Studio",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Residential",
        category: "Maisonette",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Residential",
        category: "Detached",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Residential",
        category: "Villa",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Residential",
        category: "Loft",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Residential",
        category: "Bungalow",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Residential",
        category: "Building",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Residential",
        category: "Apartment complex",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Residential",
        category: "Farm",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Residential",
        category: "Houseboat",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Residential",
        category: "Other residential",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Commercial",
        category: "Office",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Commercial",
        category: "Store",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Commercial",
        category: "Warehouse",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Commercial",
        category: "Industrial space",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Commercial",
        category: "Craft space",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Commercial",
        category: "Hotel",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Commercial",
        category: "Business building",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Commercial",
        category: "Hall",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Commercial",
        category: "Showroom",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Commercial",
        category: "Other commercial",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Land",
        category: "Plot",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Land",
        category: "Parcel",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Land",
        category: "Island",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Land",
        category: "Other land",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Other",
        category: "Parking Spot",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Other",
        category: "Business",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Other",
        category: "Prefabricated",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Other",
        category: "Detachable",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Other",
        category: "Air",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
    {
        state: "Sold/Rented",
        parentCategory: "Other",
        category: "Other",
        actions: {
            create: false,
            view: false,
            edit: false,
            delete: false,
            accessOwner: false,
            accessLocation: false,
            accessPrice: false,
            accessActive: false,
            accessInactive: false,
            accessHidden: false,
        },
    },
];
