stages:
  - Pull and Build
  - deploy

build_image:
  stage: Pull and Build
  
  tags:
    - estate-fe

  cache:
    paths:
      - node_modules/
      - .npm/

  script:
    - cd /var/www/estate-fe
    - git pull origin main
    - npm ci
  only:
    - main
