stages:
  - pull and build
  - deploy

build_image:
  stage: pull and build
  
  tags:
    - estate-fe

  cache:
    paths:
      - node_modules/
      - .npm/

  script:
    - cd /var/www/estate-fe
    - git restore .
    - git pull origin main
    - npm ci
    - npm run build
    - git restore .
  only:
    - main

deploy:
  stage: deploy
  tags:
    - estate-fe

  script:
    - export PM2_HOME="/root/.pm2"
    - pm2 restart real_estate
