sonar.projectKey=npylarinos_estate-fe
sonar.organization=npylarinos
sonar.host.url=https://sonarcloud.io
sonar.exclusions=**/i18n.ts
sonar.sourceEncoding=UTF8
sonar.javascript.lcov.reportPaths=./coverage/lcov.info