const BasicSchema = [
    {
        "owner.fullName": {
            type: "text",
            defaultValue: "\n",
            position: { x: 29.9, y: 61.91 },
            width: 86.01,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.email": {
            type: "text",
            defaultValue: "\n",
            position: { x: 125.8, y: 61.56 },
            width: 76.48,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.maidenName": {
            type: "text",
            defaultValue: "\n",
            position: { x: 47.3, y: 69.79 },
            width: 46.86,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            content: "",
        },
        "owner.idCardNumber": {
            type: "text",
            defaultValue: "\n",
            position: { x: 112.07, y: 69.47 },
            width: 42.1,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.vat": {
            type: "text",
            defaultValue: "\n",
            position: { x: 163.35, y: 69.95 },
            width: 39.18,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.city": {
            type: "text",
            defaultValue: "\n",
            position: { x: 25.17, y: 77.56 },
            width: 54.25,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.street": {
            type: "text",
            defaultValue: "\n",
            position: { x: 92.58, y: 77.51 },
            width: 89.7,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.number": {
            type: "text",
            defaultValue: "\n",
            position: { x: 189.9, y: 77.45 },
            width: 13.24,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.actingOnMyBehalf": {
            type: "text",
            defaultValue: "\n",
            position: { x: 69.45, y: 93.27 },
            width: 133.36,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.mobilePhone": {
            type: "text",
            defaultValue: "\n",
            position: { x: 12.15, y: 85.71 },
            width: 190.77,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "property.region": {
            type: "text",
            defaultValue: "\n",
            position: { x: 15.13, y: 116.98 },
            width: 40.5,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.address": {
            type: "text",
            defaultValue: "\n",
            position: { x: 69.58, y: 116.93 },
            width: 114.32,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.addressNumber": {
            type: "text",
            defaultValue: "\n",
            position: { x: 189.64, y: 116.55 },
            width: 12.18,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.type": {
            type: "text",
            defaultValue: "\n",
            position: { x: 14.48, y: 125.76 },
            width: 35.73,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.floor": {
            type: "text",
            defaultValue: "\n",
            position: { x: 59.14, y: 125.69 },
            width: 15.62,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.livingSpace": {
            type: "text",
            defaultValue: "\n",
            position: { x: 85.28, y: 125.65 },
            width: 19.06,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.description": {
            type: "text",
            defaultValue: "\n",
            position: { x: 7.97, y: 133.8 },
            width: 196.06,
            height: 7.62,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.price": {
            type: "text",
            defaultValue: "\n",
            position: { x: 36.38, y: 143.7 },
            width: 76.74,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "commissionAndDuration.payment": {
            type: "text",
            defaultValue: "\n",
            position: { x: 45.86, y: 165.6 },
            width: 88.64,
            height: 5.24,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "commissionAndDuration.flatRate": {
            type: "text",
            defaultValue: "\n",
            position: { x: 159.1, y: 164.27 },
            width: 18.53,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "commissionAndDuration.defects": {
            type: "text",
            defaultValue: "\n",
            position: { x: 135.66, y: 185.66 },
            width: 69.06,
            height: 5.24,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            content: "",
        },
        "gdpr.email": {
            type: "text",
            defaultValue: "\n",
            position: { x: 46.33, y: 230.11 },
            width: 132.04,
            height: 4.44,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "gdpr.address": {
            type: "text",
            defaultValue: "\n",
            position: { x: 8.39, y: 234.02 },
            width: 51.34,
            height: 4.44,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "additional.commissionerSignature": {
            type: "signature",
            defaultValue: "\n",
            position: { x: 6.87, y: 264.05 },
            width: 77.28,
            height: 31.43,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            strikethrough: false,
            underline: false,
            fontName: "Roboto",
        },
        "additional.agentSignature": {
            type: "signature",
            defaultValue: "\n",
            position: { x: 125.89, y: 264.27 },
            width: 79.92,
            height: 31.43,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            strikethrough: false,
            underline: false,
            fontName: "Roboto",
        },
    },
];

export default BasicSchema;
