const BasicSchema = [
    {
        "owner.fullName": {
            type: "text",
            defaultValue: "\n",
            position: { x: 29.63, y: 61.9 },
            width: 86.54,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.email": {
            type: "text",
            defaultValue: "\n",
            position: { x: 126.33, y: 61.82 },
            width: 76.21,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.maidenName": {
            type: "text",
            defaultValue: "\n",
            position: { x: 47.83, y: 69.26 },
            width: 46.06,
            height: 7.36,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            content: "",
        },
        "owner.idCardNumber": {
            type: "text",
            defaultValue: "\n",
            position: { x: 112.34, y: 69.21 },
            width: 42.89,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            content: "",
        },
        "owner.vat": {
            type: "text",
            defaultValue: "\n",
            position: { x: 163.61, y: 69.14 },
            width: 39.18,
            height: 6.57,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            content: "",
        },
        "owner.city": {
            type: "text",
            defaultValue: "\n",
            position: { x: 24.64, y: 77.28 },
            width: 57.16,
            height: 6.57,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            content: "",
        },
        "owner.street": {
            type: "text",
            defaultValue: "\n",
            position: { x: 93.11, y: 77.25 },
            width: 88.64,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            content: "",
        },
        "owner.number": {
            type: "text",
            defaultValue: "\n",
            position: { x: 190.43, y: 77.18 },
            width: 12.18,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.actingOnMyBehalf": {
            type: "text",
            defaultValue: "\n",
            position: { x: 69.19, y: 93.27 },
            width: 133.36,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.mobilePhone": {
            type: "text",
            defaultValue: "\n",
            position: { x: 14, y: 85.71 },
            width: 188.92,
            height: 6.57,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            content: "",
            fontName: "Roboto",
        },
        "property.region": {
            type: "text",
            defaultValue: "\n",
            position: { x: 14.86, y: 116.72 },
            width: 40.5,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.address": {
            type: "text",
            defaultValue: "\n",
            position: { x: 67.99, y: 116.67 },
            width: 114.32,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.addressNumber": {
            type: "text",
            defaultValue: "\n",
            position: { x: 189.9, y: 116.55 },
            width: 12.18,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.type": {
            type: "text",
            defaultValue: "\n",
            position: { x: 14.48, y: 125.76 },
            width: 35.73,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.floor": {
            type: "text",
            defaultValue: "\n",
            position: { x: 60.2, y: 125.43 },
            width: 15.62,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.livingSpace": {
            type: "text",
            defaultValue: "\n",
            position: { x: 86.08, y: 125.38 },
            width: 19.06,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.description": {
            type: "text",
            defaultValue: "\n",
            position: { x: 121.74, y: 125.32 },
            width: 82.03,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "property.price": {
            type: "text",
            defaultValue: "\n",
            position: { x: 36.65, y: 143.43 },
            width: 76.74,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "commissionAndDuration.payment": {
            type: "text",
            defaultValue: "\n",
            position: { x: 45.86, y: 165.87 },
            width: 86.79,
            height: 5.24,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "commissionAndDuration.flatRate": {
            type: "text",
            defaultValue: "\n",
            position: { x: 159.62, y: 164.53 },
            width: 18.53,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "commissionAndDuration.defects": {
            type: "text",
            defaultValue: "\n",
            position: { x: 6.65, y: 180.63 },
            width: 196.59,
            height: 5.24,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "gdpr.email": {
            type: "text",
            defaultValue: "\n",
            position: { x: 45.8, y: 225.87 },
            width: 133.63,
            height: 4.44,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            content: "",
        },
        "gdpr.address": {
            type: "text",
            defaultValue: "\n",
            position: { x: 8.39, y: 229.26 },
            width: 51.34,
            height: 4.44,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "additional.commissionerSignature": {
            type: "signature",
            defaultValue: "\n",
            position: { x: 6.87, y: 264.05 },
            width: 77.28,
            height: 31.43,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            strikethrough: false,
            underline: false,
            fontName: "Roboto",
        },
        "additional.agentSignature": {
            type: "signature",
            defaultValue: "\n",
            position: { x: 125.89, y: 264.27 },
            width: 79.92,
            height: 31.43,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            strikethrough: false,
            underline: false,
            fontName: "Roboto",
        },
    },
];

export default BasicSchema;
