const BasicSchema = [
    {
        "owner.fullName": {
            type: "text",
            defaultValue: "\n",
            position: { x: 29.9, y: 60.91 },
            width: 86.01,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            content: "",
        },
        "owner.email": {
            type: "text",
            defaultValue: "\n",
            position: { x: 125.8, y: 60.56 },
            width: 76.48,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.maidenName": {
            type: "text",
            defaultValue: "\n",
            position: { x: 47.3, y: 68.79 },
            width: 46.86,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            content: "",
        },
        "owner.idCardNumber": {
            type: "text",
            defaultValue: "\n",
            position: { x: 112.07, y: 68.47 },
            width: 42.1,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.vat": {
            type: "text",
            defaultValue: "\n",
            position: { x: 163.35, y: 68.95 },
            width: 39.18,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.city": {
            type: "text",
            defaultValue: "\n",
            position: { x: 25.17, y: 76.56 },
            width: 54.25,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.street": {
            type: "text",
            defaultValue: "\n",
            position: { x: 92.58, y: 76.51 },
            width: 89.7,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.number": {
            type: "text",
            defaultValue: "\n",
            position: { x: 189.9, y: 76.45 },
            width: 13.24,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.actingOnMyBehalf": {
            type: "text",
            defaultValue: "\n",
            position: { x: 69.45, y: 92.27 },
            width: 133.36,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.mobilePhone": {
            type: "text",
            defaultValue: "\n",
            position: { x: 12.15, y: 84.71 },
            width: 190.77,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "property.region": {
            type: "text",
            defaultValue: "\n",
            position: { x: 15.13, y: 115.98 },
            width: 40.5,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.address": {
            type: "text",
            defaultValue: "\n",
            position: { x: 69.58, y: 115.93 },
            width: 114.32,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.addressNumber": {
            type: "text",
            defaultValue: "\n",
            position: { x: 189.64, y: 115.55 },
            width: 12.18,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.type": {
            type: "text",
            defaultValue: "\n",
            position: { x: 14.48, y: 124.76 },
            width: 35.73,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.floor": {
            type: "text",
            defaultValue: "\n",
            position: { x: 59.14, y: 124.69 },
            width: 15.62,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.livingSpace": {
            type: "text",
            defaultValue: "\n",
            position: { x: 85.28, y: 124.65 },
            width: 19.06,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.description": {
            type: "text",
            defaultValue: "\n",
            position: { x: 7.97, y: 132.8 },
            width: 196.06,
            height: 7.62,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.price": {
            type: "text",
            defaultValue: "\n",
            position: { x: 36.38, y: 142.7 },
            width: 76.74,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "commissionAndDuration.flatRate": {
            type: "text",
            defaultValue: "\n",
            position: { x: 45.86, y: 164.6 },
            width: 88.64,
            height: 5.24,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "commissionAndDuration.percentage": {
            type: "text",
            defaultValue: "\n",
            position: { x: 159.1, y: 163.27 },
            width: 18.53,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "commissionAndDuration.defects": {
            type: "text",
            defaultValue: "\n",
            position: { x: 135.66, y: 184.66 },
            width: 69.06,
            height: 5.24,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            content: "",
        },
        "auto.gdprEmail": {
            type: "PROPERTY_PRO_READ_ONLY",
            defaultValue: "\n",
            position: { x: 46.33, y: 229.11 },
            width: 132.04,
            height: 4.44,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "gdpr.address": {
            type: "text",
            defaultValue: "\n",
            position: { x: 8.39, y: 233.02 },
            width: 51.34,
            height: 4.44,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "additional.commissionerSignature": {
            type: "signature",
            defaultValue: "\n",
            position: { x: 6.87, y: 264.05 },
            width: 77.28,
            height: 31.43,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            strikethrough: false,
            underline: false,
            fontName: "Roboto",
        },
        "additional.agentSignature": {
            type: "signature",
            defaultValue: "\n",
            position: { x: 125.89, y: 264.27 },
            width: 79.92,
            height: 31.43,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            strikethrough: false,
            underline: false,
            fontName: "Roboto",
        },
        "auto.day": {
            type: "PROPERTY_PRO_READ_ONLY",
            defaultValue: "\n",
            position: { x: 100.84, y: 261.13 },
            width: 4.5,
            height: 5.22,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "bottom",
            fontSize: 9,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "auto.month": {
            type: "PROPERTY_PRO_READ_ONLY",
            defaultValue: "\n",
            position: { x: 107.14, y: 260.81 },
            width: 4.49,
            height: 5.48,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "bottom",
            fontSize: 9,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "auto.year": {
            type: "PROPERTY_PRO_READ_ONLY",
            defaultValue: "\n",
            position: { x: 116.88, y: 260.75 },
            width: 5.02,
            height: 5.75,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "bottom",
            fontSize: 9,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
    },
];

export default BasicSchema;
