const BasicSchema = [
    {
        "owner.fullName": {
            type: "text",
            defaultValue: "\n",
            position: { x: 30.16, y: 60.9 },
            width: 86.01,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.email": {
            type: "text",
            defaultValue: "\n",
            position: { x: 125.8, y: 60.82 },
            width: 76.74,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.maidenName": {
            type: "text",
            defaultValue: "\n",
            position: { x: 47.83, y: 68.26 },
            width: 46.06,
            height: 7.36,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            content: "",
        },
        "owner.idCardNumber": {
            type: "text",
            defaultValue: "\n",
            position: { x: 112.61, y: 68.95 },
            width: 42.62,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            content: "",
        },
        "owner.vat": {
            type: "text",
            defaultValue: "\n",
            position: { x: 163.61, y: 68.88 },
            width: 39.18,
            height: 6.57,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            content: "",
        },
        "owner.city": {
            type: "text",
            defaultValue: "\n",
            position: { x: 24.64, y: 76.28 },
            width: 57.16,
            height: 6.57,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            content: "",
        },
        "owner.street": {
            type: "text",
            defaultValue: "\n",
            position: { x: 93.11, y: 76.25 },
            width: 88.64,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            content: "",
        },
        "owner.number": {
            type: "text",
            defaultValue: "\n",
            position: { x: 190.43, y: 76.18 },
            width: 12.18,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.actingOnMyBehalf": {
            type: "text",
            defaultValue: "\n",
            position: { x: 69.19, y: 92.27 },
            width: 133.36,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.mobilePhone": {
            type: "text",
            defaultValue: "\n",
            position: { x: 14, y: 84.71 },
            width: 188.92,
            height: 6.57,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            content: "",
            fontName: "Roboto",
        },
        "property.region": {
            type: "text",
            defaultValue: "\n",
            position: { x: 14.86, y: 115.72 },
            width: 40.5,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.address": {
            type: "text",
            defaultValue: "\n",
            position: { x: 67.99, y: 115.67 },
            width: 114.32,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.addressNumber": {
            type: "text",
            defaultValue: "\n",
            position: { x: 190.69, y: 115.55 },
            width: 11.39,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.type": {
            type: "text",
            defaultValue: "\n",
            position: { x: 15.01, y: 124.76 },
            width: 35.2,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.floor": {
            type: "text",
            defaultValue: "\n",
            position: { x: 59.41, y: 124.43 },
            width: 16.41,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.livingSpace": {
            type: "text",
            defaultValue: "\n",
            position: { x: 85.82, y: 124.38 },
            width: 19.32,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.description": {
            type: "text",
            defaultValue: "\n",
            position: { x: 8.76, y: 133.58 },
            width: 194.48,
            height: 6.55,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "property.price": {
            type: "text",
            defaultValue: "\n",
            position: { x: 36.65, y: 142.43 },
            width: 76.74,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "commissionAndDuration.flatRate": {
            type: "text",
            defaultValue: "\n",
            position: { x: 45.86, y: 164.87 },
            width: 86.79,
            height: 5.24,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "commissionAndDuration.percentage": {
            type: "text",
            defaultValue: "\n",
            position: { x: 159.62, y: 163.53 },
            width: 18.53,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "commissionAndDuration.defects": {
            type: "text",
            defaultValue: "\n",
            position: { x: 41.47, y: 180.1 },
            width: 161.93,
            height: 5.24,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "auto.gdprEmail": {
            type: "PROPERTY_PRO_READ_ONLY",
            defaultValue: "\n",
            position: { x: 45.8, y: 224.87 },
            width: 133.63,
            height: 4.44,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            content: "",
        },
        "gdpr.address": {
            type: "text",
            defaultValue: "\n",
            position: { x: 8.39, y: 228.26 },
            width: 51.34,
            height: 4.44,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "additional.commissionerSignature": {
            type: "signature",
            defaultValue: "\n",
            position: { x: 6.87, y: 264.05 },
            width: 77.28,
            height: 31.43,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            strikethrough: false,
            underline: false,
            fontName: "Roboto",
        },
        "additional.agentSignature": {
            type: "signature",
            defaultValue: "\n",
            position: { x: 125.89, y: 264.27 },
            width: 79.92,
            height: 31.43,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            strikethrough: false,
            underline: false,
            fontName: "Roboto",
        },
        "commissionAndDuration.months": {
            type: "text",
            defaultValue: "\n",
            position: { x: 178.26, y: 172.49 },
            width: 8.47,
            height: 5.24,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "auto.day": {
            type: "PROPERTY_PRO_READ_ONLY",
            defaultValue: "\n",
            position: { x: 100.84, y: 256.89 },
            width: 5.03,
            height: 5.22,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "bottom",
            fontSize: 9,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "auto.month": {
            type: "PROPERTY_PRO_READ_ONLY",
            defaultValue: "\n",
            position: { x: 107.14, y: 256.84 },
            width: 5.02,
            height: 5.49,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "bottom",
            fontSize: 9,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "auto.year": {
            type: "PROPERTY_PRO_READ_ONLY",
            defaultValue: "\n",
            position: { x: 116.88, y: 257.04 },
            width: 5.3,
            height: 5.22,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "bottom",
            fontSize: 9,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
    },
];

export default BasicSchema;
