const BasicSchema = [
    {
        "owner.fullName": {
            type: "text",
            defaultValue: "\n",
            position: { x: 29.37, y: 62.17 },
            width: 86.27,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.email": {
            type: "text",
            defaultValue: "\n",
            position: { x: 125.54, y: 61.82 },
            width: 77.27,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.maidenName": {
            type: "text",
            defaultValue: "\n",
            position: { x: 47.83, y: 69.79 },
            width: 45,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.idCardNumber": {
            type: "text",
            defaultValue: "\n",
            position: { x: 112.08, y: 69.74 },
            width: 42.36,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.vat": {
            type: "text",
            defaultValue: "\n",
            position: { x: 163.08, y: 69.95 },
            width: 39.71,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            content: "",
        },
        "owner.city": {
            type: "text",
            defaultValue: "\n",
            position: { x: 24.38, y: 77.56 },
            width: 55.84,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.street": {
            type: "text",
            defaultValue: "\n",
            position: { x: 92.84, y: 77.52 },
            width: 89.7,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.number": {
            type: "text",
            defaultValue: "\n",
            position: { x: 190.96, y: 77.44 },
            width: 12.18,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.actingOnMyBehalf": {
            type: "text",
            defaultValue: "\n",
            position: { x: 69.19, y: 93.27 },
            width: 134.15,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.mobilePhone": {
            type: "text",
            defaultValue: "\n",
            position: { x: 13.07, y: 85.82 },
            width: 190.27,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "commissionAndDuration.payment": {
            type: "text",
            defaultValue: "\n",
            position: { x: 47.18, y: 183.33 },
            width: 87.05,
            height: 5.24,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "commissionAndDuration.percentage": {
            type: "text",
            defaultValue: "\n",
            position: { x: 163.6, y: 182 },
            width: 18.53,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
            content: "",
        },
        "commissionAndDuration.defects": {
            type: "text",
            defaultValue: "\n",
            position: { x: 135.66, y: 202.86 },
            width: 68.27,
            height: 5.24,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "gdpr.email": {
            type: "text",
            defaultValue: "\n",
            position: { x: 47.01, y: 246.78 },
            width: 132.04,
            height: 4.44,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "gdpr.address": {
            type: "text",
            defaultValue: "\n",
            position: { x: 8.14, y: 250.41 },
            width: 50.28,
            height: 4.44,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            content: "",
        },
        "additional.commissionerSignature": {
            type: "signature",
            defaultValue: "\n",
            position: { x: 6.87, y: 264.05 },
            width: 77.28,
            height: 31.43,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            strikethrough: false,
            underline: false,
            fontName: "Roboto",
        },
        "additional.agentSignature": {
            type: "signature",
            defaultValue: "\n",
            position: { x: 125.89, y: 264.27 },
            width: 79.92,
            height: 31.43,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            strikethrough: false,
            underline: false,
            fontName: "Roboto",
        },
        "suggestedProperties.0.area": {
            type: "text",
            defaultValue: "\n",
            position: { x: 6.92, y: 132.08 },
            width: 25.15,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.0.address": {
            type: "text",
            defaultValue: "\n",
            position: { x: 32.26, y: 132.03 },
            width: 67.22,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.0.type": {
            type: "text",
            defaultValue: "\n",
            position: { x: 99.2, y: 132.04 },
            width: 30.18,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.0.livingSpace": {
            type: "text",
            defaultValue: "\n",
            position: { x: 129.32, y: 131.99 },
            width: 22.5,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.0.price": {
            type: "text",
            defaultValue: "\n",
            position: { x: 151.48, y: 131.93 },
            width: 29.91,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.0.fee": {
            type: "text",
            defaultValue: "\n",
            position: { x: 181.85, y: 132.14 },
            width: 22.24,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.1.area": {
            type: "text",
            defaultValue: "\n",
            position: { x: 6.87, y: 140.23 },
            width: 25.15,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
            content: "",
        },
        "suggestedProperties.1.address": {
            type: "text",
            defaultValue: "\n",
            position: { x: 31.95, y: 140.18 },
            width: 67.48,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.1.type": {
            type: "text",
            defaultValue: "\n",
            position: { x: 99.42, y: 140.19 },
            width: 29.91,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.1.livingSpace": {
            type: "text",
            defaultValue: "\n",
            position: { x: 129.27, y: 140.14 },
            width: 22.5,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
            content: "",
        },
        "suggestedProperties.1.price": {
            type: "text",
            defaultValue: "\n",
            position: { x: 151.69, y: 140.08 },
            width: 30.44,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.1.fee": {
            type: "text",
            defaultValue: "\n",
            position: { x: 181.69, y: 140.29 },
            width: 21.97,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.2.area": {
            type: "text",
            defaultValue: "\n",
            position: { x: 6.55, y: 146.79 },
            width: 25.15,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.2.address": {
            type: "text",
            defaultValue: "\n",
            position: { x: 31.89, y: 146.74 },
            width: 67.49,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.2.type": {
            type: "text",
            defaultValue: "\n",
            position: { x: 99.36, y: 146.75 },
            width: 29.91,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.2.livingSpace": {
            type: "text",
            defaultValue: "\n",
            position: { x: 129.48, y: 146.7 },
            width: 22.76,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.2.price": {
            type: "text",
            defaultValue: "\n",
            position: { x: 151.64, y: 146.64 },
            width: 30.18,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.2.fee": {
            type: "text",
            defaultValue: "\n",
            position: { x: 181.95, y: 146.85 },
            width: 21.71,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.3.area": {
            type: "text",
            defaultValue: "\n",
            position: { x: 6.5, y: 153.88 },
            width: 25.15,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.3.address": {
            type: "text",
            defaultValue: "\n",
            position: { x: 31.84, y: 153.83 },
            width: 67.75,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.3.type": {
            type: "text",
            defaultValue: "\n",
            position: { x: 99.58, y: 153.84 },
            width: 29.64,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.3.livingSpace": {
            type: "text",
            defaultValue: "\n",
            position: { x: 129.42, y: 153.79 },
            width: 22.5,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.3.price": {
            type: "text",
            defaultValue: "\n",
            position: { x: 152.38, y: 153.73 },
            width: 29.65,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.3.fee": {
            type: "text",
            defaultValue: "\n",
            position: { x: 181.97, y: 153.94 },
            width: 21.97,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
    },
];

export default BasicSchema;
