import { IDemandPOST } from "@/types/demand";

const EMTPY_DEMAND: IDemandPOST = {
    filters: {
        labels: [],
        regions: [],
        cities: [],
        complexes: [],
        states: [],
        categories: [],
        parentCategories: [],
        furnished: [],

        minPlot: 0,
        maxPlot: 0,
        minPrice: 0,
        maxPrice: 0,
        minBathrooms: 0,
        maxBathrooms: 0,
        minCovered: 0,
        maxCovered: 0,
        minBedrooms: 0,
        maxBedrooms: 0,
        minYearOfConstruction: 0,
        maxYearOfConstruction: 0,
        minFloor: null, // INFO: Backend works with this as unset
        maxFloor: null, // INFO: Backend works with this as unset
    },
    priorityFeatures: {
        panoramicView: false,
        seaView: false,
        mountainView: false,
        seaFront: false,
        walkableDistanceToBeach: false,
        quietArea: false,
        bright: false,
        nearBusRoute: false,
        smartHome: false,
        guestroom: false,
        office: false,
        homeCinema: false,
        combinedKitchenAndDiningArea: false,
        soundInsulation: false,
        thermalInsulation: false,
        heatedPool: false,
        indoorPool: false,
        organizedGarden: false,
        jacuzzi: false,
        well: false,
        drilling: false,
        masonryFence: false,
        accessForDisabled: false,
        alarmSystem: false,
        has24HoursSecurity: false,
        cctv: false,
        internet: false,
        fireDetector: false,
        independentHeatingPerRoom: false,
        adaptingToTheGround: false,
        barbeque: false,
        pool: false,
        view: false,
        facade: false,
        corner: false,
        veranda: false,
        tents: false,
        withinResidentialZone: false,
        withinCityPlan: false,
        loadingDock: false,
    },
    shapeList: [],
    timeframe: null, // INFO: Backend works with this as unset
};

export { EMTPY_DEMAND };
