const BasicSchema = [
    {
        "owner.fullName": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 38.1,
                y: 60.85,
            },
            width: 93.68,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.email": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 141.41,
                y: 60.24,
            },
            width: 61.13,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.maidenName": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 30.37,
                y: 68.47,
            },
            width: 65.64,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.idCardNumber": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 105.46,
                y: 68.15,
            },
            width: 96.6,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.vat": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 16.5,
                y: 76.56,
            },
            width: 40.5,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.city": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 69.09,
                y: 76.24,
            },
            width: 30.97,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.street": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 108.19,
                y: 76.19,
            },
            width: 73.56,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.number": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 189.9,
                y: 76.39,
            },
            width: 12.18,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.actingOnMyBehalf": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 65.75,
                y: 83.75,
            },
            width: 136.27,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.region": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 18.83,
                y: 111.16,
            },
            width: 40.5,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.address": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 67.46,
                y: 111.11,
            },
            width: 114.32,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.addressNumber": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 190.69,
                y: 110.73,
            },
            width: 12.18,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.type": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 15.27,
                y: 120.2,
            },
            width: 35.73,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.floor": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 63.64,
                y: 120.14,
            },
            width: 15.62,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.livingSpace": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 93.75,
                y: 120.09,
            },
            width: 19.06,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.description": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 7.18,
                y: 127.71,
            },
            width: 196.06,
            height: 7.62,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.price": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 36.65,
                y: 138.14,
            },
            width: 76.74,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "commissionAndDuration.payment": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 60.41,
                y: 161.37,
            },
            width: 88.64,
            height: 5.24,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "commissionAndDuration.flatRate": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 171.27,
                y: 158.71,
            },
            width: 18.53,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "commissionAndDuration.defects": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 6.65,
                y: 180.63,
            },
            width: 196.59,
            height: 5.24,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "gdpr.email": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 84.96,
                y: 225.61,
            },
            width: 118.81,
            height: 4.44,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "gdpr.address": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 23.21,
                y: 228.73,
            },
            width: 40.49,
            height: 4.44,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },

        "additional.commissionerSignature": {
            type: "signature",
            defaultValue: "\n",
            position: { x: 6.87, y: 264.05 },
            width: 77.28,
            height: 31.43,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            strikethrough: false,
            underline: false,
            fontName: "Roboto",
        },
        "additional.agentSignature": {
            type: "signature",
            defaultValue: "\n",
            position: { x: 125.89, y: 264.27 },
            width: 79.92,
            height: 31.43,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "bottom",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            strikethrough: false,
            underline: false,
            fontName: "Roboto",
        },
    },
];

export default BasicSchema;
