const BasicExclusive = [
    {
        "owner.fullName": {
            type: "text",
            content: "\n",
            position: { x: 37.58, y: 60.85 },
            width: 94.74,
            height: 7.89,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "owner.email": {
            type: "text",
            content: "\n",
            position: { x: 141.13, y: 60.81 },
            width: 61.67,
            height: 7.89,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "owner.maidenName": {
            type: "text",
            content: "\n",
            position: { x: 31.39, y: 68.68 },
            width: 29.92,
            height: 7.89,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "owner.idCardNumber": {
            type: "text",
            content: "\n",
            position: { x: 70.49, y: 68.89 },
            width: 39.44,
            height: 7.89,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "owner.mobilePhone": {
            type: "text",
            content: "\n",
            position: { x: 117.54, y: 69.1 },
            width: 84.95,
            height: 7.89,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "owner.vat": {
            type: "text",
            content: "\n",
            position: { x: 18.11, y: 76.83 },
            width: 38.13,
            height: 7.89,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "owner.city": {
            type: "text",
            content: "\n",
            position: { x: 69.39, y: 76.78 },
            width: 29.93,
            height: 7.89,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "owner.street": {
            type: "text",
            content: "\n",
            position: { x: 108.49, y: 77.25 },
            width: 72.53,
            height: 7.89,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "owner.number": {
            type: "text",
            content: "\n",
            position: { x: 189.87, y: 77.2 },
            width: 13,
            height: 7.89,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "owner.actingOnMyBehalf": {
            type: "text",
            content: "\n",
            position: { x: 65.57, y: 84.61 },
            width: 137.35,
            height: 7.89,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "property.region": {
            type: "text",
            content: "\n",
            position: { x: 18.37, y: 111.49 },
            width: 41.03,
            height: 7.89,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "property.address": {
            type: "text",
            content: "\n",
            position: { x: 68.06, y: 111.17 },
            width: 112.99,
            height: 7.89,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "property.addressNumber": {
            type: "text",
            content: "\n",
            position: { x: 190.9433728, y: 111.12 },
            width: 11.13,
            height: 7.89,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "property.type": {
            type: "text",
            content: "\n",
            position: { x: 15.4, y: 120.17 },
            width: 35.48,
            height: 7.89,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "property.floor": {
            type: "text",
            content: "\n",
            position: { x: 62.71, y: 119.85 },
            width: 17.22,
            height: 7.89,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "property.livingSpace": {
            type: "text",
            content: "\n",
            position: { x: 93.34, y: 119.8 },
            width: 20.4,
            height: 7.89,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "property.description": {
            type: "text",
            content: "\n",
            position: { x: 6.77, y: 128.47 },
            width: 195.29,
            height: 7.89,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "property.price": {
            type: "text",
            content: "\n",
            position: { x: 35.36, y: 137.73 },
            width: 80.72,
            height: 7.89,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "commissionAndDuration.payment": {
            type: "text",
            content: "\n",
            position: { x: 60.7, y: 162.81 },
            width: 87.87,
            height: 7.89,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "commissionAndDuration.percentage": {
            type: "text",
            content: "\n",
            position: { x: 171.37, y: 162.4 },
            width: 18.01,
            height: 7.89,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "commissionAndDuration.months": {
            type: "text",
            content: "\n",
            position: { x: 169.99, y: 173.99 },
            width: 9.81,
            height: 7.89,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "commissionAndDuration.defects": {
            type: "text",
            content: "\n",
            position: { x: 7.47, y: 185.77 },
            width: 196.35,
            height: 7.89,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "gdpr.email": {
            type: "text",
            content: "\n",
            position: { x: 84.46, y: 232.34 },
            width: 95.54,
            height: 5.77,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "middle",
            fontSize: 9,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "gdpr.address": {
            type: "text",
            content: "\n",
            position: { x: 25.67, y: 235.2 },
            width: 36.54,
            height: 5.77,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "middle",
            fontSize: 9,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
    },
];

export default BasicExclusive;
