const BasicExclusive = [
    {
        "owner.fullName": {
            type: "text",
            content: "\n",
            position: { x: 37.58, y: 59.85 },
            width: 94.74,
            height: 7.89,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "owner.email": {
            type: "text",
            content: "\n",
            position: { x: 141.13, y: 59.81 },
            width: 61.67,
            height: 7.89,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "owner.maidenName": {
            type: "text",
            content: "\n",
            position: { x: 31.92, y: 68.48 },
            width: 29.39,
            height: 7.09,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "owner.idCardNumber": {
            type: "text",
            content: "\n",
            position: { x: 70.49, y: 68.48 },
            width: 39.44,
            height: 6.3,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "owner.mobilePhone": {
            type: "text",
            content: "\n",
            position: { x: 117.54, y: 68.69 },
            width: 84.95,
            height: 6.3,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "owner.vat": {
            type: "text",
            content: "\n",
            position: { x: 18.11, y: 76.68 },
            width: 38.13,
            height: 6.04,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "owner.city": {
            type: "text",
            content: "\n",
            position: { x: 70.19, y: 76.11 },
            width: 29.13,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "owner.street": {
            type: "text",
            content: "\n",
            position: { x: 108.49, y: 76.31 },
            width: 72.53,
            height: 6.83,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "owner.number": {
            type: "text",
            content: "\n",
            position: { x: 190.14, y: 76.26 },
            width: 12.73,
            height: 6.83,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "owner.actingOnMyBehalf": {
            type: "text",
            content: "\n",
            position: { x: 65.57, y: 84.2 },
            width: 137.35,
            height: 6.3,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "property.region": {
            type: "text",
            content: "\n",
            position: { x: 18.37, y: 111.03 },
            width: 41.03,
            height: 7.09,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "property.address": {
            type: "text",
            content: "\n",
            position: { x: 68.06, y: 111.23 },
            width: 112.99,
            height: 6.83,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "property.addressNumber": {
            type: "text",
            content: "\n",
            position: { x: 190.94, y: 111.18 },
            width: 11.13,
            height: 6.83,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "property.type": {
            type: "text",
            content: "\n",
            position: { x: 15.4, y: 120.23 },
            width: 35.48,
            height: 6.83,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "property.floor": {
            type: "text",
            content: "\n",
            position: { x: 63.24, y: 119.91 },
            width: 16.69,
            height: 6.83,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "property.livingSpace": {
            type: "text",
            content: "\n",
            position: { x: 93.34, y: 119.86 },
            width: 20.4,
            height: 6.83,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "property.description": {
            type: "text",
            content: "\n",
            position: { x: 7.57, y: 127.94 },
            width: 194.49,
            height: 7.89,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "property.price": {
            type: "text",
            content: "",
            position: { x: 35.63, y: 137.52 },
            width: 80.45,
            height: 7.09,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "commissionAndDuration.flatRate": {
            type: "text",
            content: "\n",
            position: { x: 60.7, y: 163.13 },
            width: 87.87,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "commissionAndDuration.percentage": {
            type: "text",
            content: "\n",
            position: { x: 171.37, y: 162.99 },
            width: 18.01,
            height: 6.3,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "commissionAndDuration.months": {
            type: "text",
            content: "\n",
            position: { x: 170.79, y: 174.26 },
            width: 8.21,
            height: 7.09,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "commissionAndDuration.defects": {
            type: "text",
            content: "\n",
            position: { x: 8, y: 186.62 },
            width: 195.82,
            height: 6.04,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "auto.gdprEmail": {
            type: "PROPERTY_PRO_READ_ONLY",
            content: "\n",
            position: { x: 84.46, y: 231.34 },
            width: 95.54,
            height: 5.77,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 9,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "gdpr.address": {
            type: "text",
            content: "\n",
            position: { x: 25.67, y: 234.2 },
            width: 36.54,
            height: 5.77,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 9,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "additional.commissionerSignature": {
            type: "signature",
            defaultValue: "\n",
            position: { x: 6.87, y: 264.05 },
            width: 77.28,
            height: 31.43,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            strikethrough: false,
            underline: false,
            fontName: "Roboto",
        },
        "additional.agentSignature": {
            type: "signature",
            defaultValue: "\n",
            position: { x: 125.89, y: 264.27 },
            width: 79.92,
            height: 31.43,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            strikethrough: false,
            underline: false,
            fontName: "Roboto",
        },
        "auto.day": {
            type: "PROPERTY_PRO_READ_ONLY",
            defaultValue: "\n",
            position: { x: 100.57, y: 268 },
            width: 3.71,
            height: 4.7,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "bottom",
            fontSize: 9,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "auto.month": {
            type: "PROPERTY_PRO_READ_ONLY",
            defaultValue: "\n",
            position: { x: 106.87, y: 267.95 },
            width: 4.23,
            height: 4.7,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "bottom",
            fontSize: 9,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "auto.year": {
            type: "PROPERTY_PRO_READ_ONLY",
            defaultValue: "\n",
            position: { x: 116.61, y: 268.15 },
            width: 3.97,
            height: 4.7,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "bottom",
            fontSize: 9,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
    },
];

export default BasicExclusive;
