const BasicSchema = [
    {
        "owner.fullName": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 38.1,
                y: 60.85,
            },
            width: 93.68,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.email": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 141.41,
                y: 60.24,
            },
            width: 61.13,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.maidenName": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 30.37,
                y: 68.47,
            },
            width: 35.64,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.idCardNumber": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 75.96,
                y: 68.15,
            },
            width: 46.6,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.mobilePhone": {
            type: "text",
            content: "\n",
            position: { x: 127.54, y: 68.15 },
            width: 74.45,
            height: 7.89,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },

        "owner.vat": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 16.5,
                y: 76.56,
            },
            width: 40.5,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },

        "owner.city": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 69.09,
                y: 76.24,
            },
            width: 30.97,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.street": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 108.19,
                y: 76.19,
            },
            width: 73.56,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.number": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 193.9,
                y: 76.39,
            },
            width: 9.18,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.actingOnMyBehalf": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 65.75,
                y: 83.75,
            },
            width: 136.27,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.region": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 15.83,
                y: 109.16,
            },
            width: 40.5,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.address": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 31.46,
                y: 130.11,
            },
            width: 74.32,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.addressNumber": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 182.69,
                y: 130.14,
            },
            width: 22.18,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.type": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 107.76,
                y: 130.14,
            },
            width: 23.73,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.floor": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 8.64,
                y: 130.14,
            },
            width: 15.62,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.livingSpace": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 132.75,
                y: 130.89,
            },
            width: 19.06,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },

        "property.price": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 154.05,
                y: 130.14,
            },
            width: 23.73,

            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "commissionAndDuration.payment": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 7.41,
                y: 190.37,
            },
            width: 88.64,
            height: 4.24,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "commissionAndDuration.flatRate": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 116.27,
                y: 190.37,
            },
            width: 18.53,
            height: 4.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "commissionAndDuration.defects": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 122.27,
                y: 210.63,
            },
            width: 82.59,
            height: 3.24,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "gdpr.email": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 138.96,
                y: 235.91,
            },
            width: 40.81,
            height: 3.24,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "gdpr.address": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 87.21,
                y: 253.73,
            },
            width: 38.49,
            height: 3.44,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "property.description": {
            type: "text",

            defaultValue: "\n",
            position: {
                x: 144.21,
                y: 253.73,
            },
            width: 54.4,
            height: 3.62,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 13,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
    },
];

export default BasicSchema;
