const BasicSchema = [
    {
        "owner.fullName": {
            type: "text",
            defaultValue: "\n",
            position: { x: 38.1, y: 60.64 },
            width: 93.68,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.email": {
            type: "text",
            defaultValue: "\n",
            position: { x: 142.21, y: 60.56 },
            width: 60.33,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.maidenName": {
            type: "text",
            defaultValue: "\n",
            position: { x: 32.22, y: 68.73 },
            width: 36.27,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            content: "",
        },
        "owner.idCardNumber": {
            type: "text",
            defaultValue: "\n",
            position: { x: 78.21, y: 68.68 },
            width: 42.89,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.vat": {
            type: "text",
            defaultValue: "\n",
            position: { x: 18.09, y: 76.3 },
            width: 40.5,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.city": {
            type: "text",
            defaultValue: "\n",
            position: { x: 70.94, y: 76.24 },
            width: 29.65,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.street": {
            type: "text",
            defaultValue: "\n",
            position: { x: 109.25, y: 76.46 },
            width: 72.76,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.number": {
            type: "text",
            defaultValue: "\n",
            position: { x: 194.39, y: 76.65 },
            width: 7.69,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.actingOnMyBehalf": {
            type: "text",
            defaultValue: "\n",
            position: { x: 65.75, y: 83.75 },
            width: 136.27,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.mobilePhone": {
            type: "text",
            defaultValue: "\n",
            position: { x: 130.02, y: 68.68 },
            width: 72.79,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "commissionAndDuration.flatRate": {
            type: "text",
            defaultValue: "\n",
            position: { x: 8.55, y: 189.21 },
            width: 87.85,
            height: 5.24,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "commissionAndDuration.percentage": {
            type: "text",
            defaultValue: "\n",
            position: { x: 116.77, y: 189.74 },
            width: 18.53,
            height: 4.7,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "commissionAndDuration.defects": {
            type: "text",
            defaultValue: "\n",
            position: { x: 124.02, y: 208.74 },
            width: 79.38,
            height: 5.24,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "auto.gdprEmail": {
            type: "PROPERTY_PRO_READ_ONLY",
            defaultValue: "\n",
            position: { x: 88.02, y: 252.92 },
            width: 37.05,
            height: 4.44,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "gdpr.address": {
            type: "text",
            defaultValue: "\n",
            position: { x: 147.04, y: 253.12 },
            width: 50.28,
            height: 4.44,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            content: "",
        },
        "additional.commissionerSignature": {
            type: "signature",
            defaultValue: "\n",
            position: { x: 6.87, y: 264.05 },
            width: 77.28,
            height: 31.43,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            strikethrough: false,
            underline: false,
            fontName: "Roboto",
        },
        "additional.agentSignature": {
            type: "signature",
            defaultValue: "\n",
            position: { x: 125.89, y: 264.27 },
            width: 79.92,
            height: 31.43,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            strikethrough: false,
            underline: false,
            fontName: "Roboto",
        },
        "suggestedProperties.0.area": {
            type: "PROPERTY_PRO_SUGGEST_BUTTON",
            defaultValue: "\n",
            position: { x: 7.98, y: 131.08 },
            width: 21.71,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.0.address": {
            type: "text",
            defaultValue: "\n",
            position: { x: 30.41, y: 131.03 },
            width: 75.95,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.0.type": {
            type: "text",
            defaultValue: "\n",
            position: { x: 108.2, y: 131.04 },
            width: 23.56,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.0.livingSpace": {
            type: "text",
            defaultValue: "\n",
            position: { x: 133.29, y: 130.99 },
            width: 20.91,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.0.price": {
            type: "text",
            defaultValue: "\n",
            position: { x: 155.45, y: 130.93 },
            width: 23.56,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.0.fee": {
            type: "text",
            defaultValue: "\n",
            position: { x: 180.53, y: 131.14 },
            width: 23.56,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.1.area": {
            type: "PROPERTY_PRO_SUGGEST_BUTTON",
            defaultValue: "\n",
            position: { x: 7.93, y: 139.23 },
            width: 21.71,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.1.address": {
            type: "text",
            defaultValue: "\n",
            position: { x: 30.63, y: 139.18 },
            width: 75.68,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.1.type": {
            type: "text",
            defaultValue: "\n",
            position: { x: 108.15, y: 139.19 },
            width: 23.56,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.1.livingSpace": {
            type: "text",
            defaultValue: "\n",
            position: { x: 133.24, y: 139.14 },
            width: 20.91,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.1.price": {
            type: "text",
            defaultValue: "\n",
            position: { x: 155.66, y: 139.08 },
            width: 23.3,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.1.fee": {
            type: "text",
            defaultValue: "\n",
            position: { x: 180.63, y: 139.29 },
            width: 23.03,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.2.area": {
            type: "PROPERTY_PRO_SUGGEST_BUTTON",
            defaultValue: "\n",
            position: { x: 7.88, y: 145.79 },
            width: 21.44,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.2.address": {
            type: "text",
            defaultValue: "\n",
            position: { x: 30.31, y: 145.74 },
            width: 75.68,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.2.type": {
            type: "text",
            defaultValue: "\n",
            position: { x: 108.09, y: 145.75 },
            width: 23.3,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.2.livingSpace": {
            type: "text",
            defaultValue: "\n",
            position: { x: 133.44, y: 145.7 },
            width: 20.39,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.2.price": {
            type: "text",
            defaultValue: "\n",
            position: { x: 155.87, y: 145.64 },
            width: 22.77,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.2.fee": {
            type: "text",
            defaultValue: "\n",
            position: { x: 180.62, y: 145.86 },
            width: 23.04,
            height: 6.55,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.3.area": {
            type: "PROPERTY_PRO_SUGGEST_BUTTON",
            defaultValue: "\n",
            position: { x: 7.56, y: 152.88 },
            width: 21.71,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.3.address": {
            type: "text",
            defaultValue: "\n",
            position: { x: 30.26, y: 152.83 },
            width: 75.68,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.3.type": {
            type: "text",
            defaultValue: "\n",
            position: { x: 108.31, y: 152.84 },
            width: 23.03,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.3.livingSpace": {
            type: "text",
            defaultValue: "\n",
            position: { x: 133.65, y: 152.79 },
            width: 20.12,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.3.price": {
            type: "text",
            defaultValue: "\n",
            position: { x: 155.82, y: 152.73 },
            width: 22.77,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.3.fee": {
            type: "text",
            defaultValue: "\n",
            position: { x: 180.64, y: 152.94 },
            width: 23.3,
            height: 6.56,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "auto.day": {
            type: "PROPERTY_PRO_READ_ONLY",
            defaultValue: "\n",
            position: { x: 100.84, y: 270.38 },
            width: 3.71,
            height: 4.7,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "bottom",
            fontSize: 9,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "auto.month": {
            type: "PROPERTY_PRO_READ_ONLY",
            defaultValue: "\n",
            position: { x: 107.14, y: 270.33 },
            width: 4.23,
            height: 4.7,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "bottom",
            fontSize: 9,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "auto.year": {
            type: "PROPERTY_PRO_READ_ONLY",
            defaultValue: "\n",
            position: { x: 116.88, y: 270.53 },
            width: 3.97,
            height: 4.7,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "bottom",
            fontSize: 9,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        suggestedProperties: {
            type: "PROPERTY_PRO_ERROR_TOOLTIP",
            defaultValue: "\n",
            position: { x: 119.63, y: 119.31 },
            width: 12.44,
            height: 5.23,
            rotate: 0,
            alignment: "center",
            verticalAlignment: "middle",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
    },
];

export default BasicSchema;
