const BasicSchema = [
    {
        "owner.fullName": {
            type: "text",
            defaultValue: "\n",
            position: { x: 38.1, y: 61.64 },
            width: 93.68,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.email": {
            type: "text",
            defaultValue: "\n",
            position: { x: 141.41, y: 61.56 },
            width: 61.13,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.maidenName": {
            type: "text",
            defaultValue: "\n",
            position: { x: 31.69, y: 69.26 },
            width: 36.8,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.idCardNumber": {
            type: "text",
            defaultValue: "\n",
            position: { x: 78.21, y: 69.21 },
            width: 42.89,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.vat": {
            type: "text",
            defaultValue: "\n",
            position: { x: 18.09, y: 77.36 },
            width: 40.5,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.city": {
            type: "text",
            defaultValue: "\n",
            position: { x: 69.62, y: 77.03 },
            width: 30.97,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.street": {
            type: "text",
            defaultValue: "\n",
            position: { x: 108.45, y: 76.99 },
            width: 73.56,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.number": {
            type: "text",
            defaultValue: "\n",
            position: { x: 193.6, y: 77.18 },
            width: 8.48,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.actingOnMyBehalf": {
            type: "text",
            defaultValue: "\n",
            position: { x: 65.75, y: 83.75 },
            width: 136.27,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "owner.mobilePhone": {
            type: "text",
            defaultValue: "\n",
            position: { x: 130.02, y: 69.68 },
            width: 72.79,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "commissionAndDuration.payment": {
            type: "text",
            defaultValue: "\n",
            position: { x: 7.76, y: 190.21 },
            width: 88.64,
            height: 5.24,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "commissionAndDuration.percentage": {
            type: "text",
            defaultValue: "\n",
            position: { x: 116.77, y: 188.88 },
            width: 18.53,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "commissionAndDuration.defects": {
            type: "text",
            defaultValue: "\n",
            position: { x: 124.02, y: 209.74 },
            width: 79.38,
            height: 5.24,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "gdpr.email": {
            type: "text",
            defaultValue: "\n",
            position: { x: 88.02, y: 253.92 },
            width: 37.05,
            height: 4.44,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
        },
        "gdpr.address": {
            type: "text",
            defaultValue: "\n",
            position: { x: 147.04, y: 254.12 },
            width: 50.28,
            height: 4.44,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            content: "",
        },
        "additional.commissionerSignature": {
            type: "signature",
            defaultValue: "\n",
            position: { x: 6.87, y: 264.05 },
            width: 77.28,
            height: 31.43,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            strikethrough: false,
            underline: false,
            fontName: "Roboto",
        },
        "additional.agentSignature": {
            type: "signature",
            defaultValue: "\n",
            position: { x: 125.89, y: 264.27 },
            width: 79.92,
            height: 31.43,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            strikethrough: false,
            underline: false,
            fontName: "Roboto",
        },
        "suggestedProperties.0.area": {
            type: "text",
            defaultValue: "\n",
            position: { x: 6.92, y: 132.08 },
            width: 22.77,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.0.address": {
            type: "text",
            defaultValue: "\n",
            position: { x: 30.41, y: 132.03 },
            width: 75.95,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.0.type": {
            type: "text",
            defaultValue: "\n",
            position: { x: 107.14, y: 132.04 },
            width: 24.62,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.0.livingSpace": {
            type: "text",
            defaultValue: "\n",
            position: { x: 131.96, y: 131.99 },
            width: 22.24,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.0.price": {
            type: "text",
            defaultValue: "\n",
            position: { x: 154.39, y: 131.93 },
            width: 24.62,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.0.fee": {
            type: "text",
            defaultValue: "\n",
            position: { x: 179.47, y: 132.14 },
            width: 24.62,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.1.area": {
            type: "text",
            defaultValue: "\n",
            position: { x: 6.87, y: 140.23 },
            width: 22.77,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.1.address": {
            type: "text",
            defaultValue: "\n",
            position: { x: 30.36, y: 140.18 },
            width: 75.95,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.1.type": {
            type: "text",
            defaultValue: "\n",
            position: { x: 107.09, y: 140.19 },
            width: 24.62,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.1.livingSpace": {
            type: "text",
            defaultValue: "\n",
            position: { x: 131.91, y: 140.14 },
            width: 22.24,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.1.price": {
            type: "text",
            defaultValue: "\n",
            position: { x: 154.34, y: 140.08 },
            width: 24.62,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.1.fee": {
            type: "text",
            defaultValue: "\n",
            position: { x: 179.04, y: 140.29 },
            width: 24.62,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.2.area": {
            type: "text",
            defaultValue: "\n",
            position: { x: 6.55, y: 146.79 },
            width: 22.77,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.2.address": {
            type: "text",
            defaultValue: "\n",
            position: { x: 30.04, y: 146.74 },
            width: 75.95,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.2.type": {
            type: "text",
            defaultValue: "\n",
            position: { x: 106.77, y: 146.75 },
            width: 24.62,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.2.livingSpace": {
            type: "text",
            defaultValue: "\n",
            position: { x: 131.59, y: 146.7 },
            width: 22.24,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.2.price": {
            type: "text",
            defaultValue: "\n",
            position: { x: 154.02, y: 146.64 },
            width: 24.62,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.2.fee": {
            type: "text",
            defaultValue: "\n",
            position: { x: 179.04, y: 146.85 },
            width: 24.62,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.3.area": {
            type: "text",
            defaultValue: "\n",
            position: { x: 6.5, y: 153.88 },
            width: 22.77,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.3.address": {
            type: "text",
            defaultValue: "\n",
            position: { x: 29.99, y: 153.83 },
            width: 75.95,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.3.type": {
            type: "text",
            defaultValue: "\n",
            position: { x: 106.72, y: 153.84 },
            width: 24.62,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.3.livingSpace": {
            type: "text",
            defaultValue: "\n",
            position: { x: 131.53, y: 153.79 },
            width: 22.24,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.3.price": {
            type: "text",
            defaultValue: "\n",
            position: { x: 153.97, y: 153.73 },
            width: 24.62,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
        "suggestedProperties.3.fee": {
            type: "text",
            defaultValue: "\n",
            position: { x: 179.32, y: 153.94 },
            width: 24.62,
            height: 6.56,
            rotate: 0,
            alignment: "left",
            verticalAlignment: "top",
            fontSize: 11,
            lineHeight: 1,
            characterSpacing: 0,
            fontColor: "#000000",
            backgroundColor: "",
            opacity: 1,
            fontName: "Roboto",
        },
    },
];

export default BasicSchema;
